### ISSUE TITLE
Macro with gcode and other macros running out of order

### ISSUE THREAD

**Issue by napter** [cp2004/OctoPrint-GCodeMacros#9]
I have Macro A which looks like this:

some Gcode
@MacroB
someGcode
@MacroC

But it gets sent to the printer out of order. The GCode within the script executes first and the referenced macros are tacked on to the end like this:

Some Gcode
Some Gcode
@MacroB
@MacroC

**Comment by cp2004** [comment]
Hmm, at first I didn't believe this but after testing I can indeed reproduce the issue...

I'll take a look and see what I can do.

**Comment by cp2004** [comment]
That should now be fixed with 1.1.2.
